apiVersion: v1
kind: Template
metadata:
  name: launchpad-builder
  annotations:
    description: This template creates a Build Configuration using an S2I builder.
    tags: instant-app
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: minecraft-server
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: docker.io/edewit/minecraft-osgi-plugin-s2i
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: minecraft-server
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: minecraft-server:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      #contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/health-check-vertx
      prometheus.io/port: "9779"
      fabric8.io/scm-url: https://github.com/openshiftio/health-check-vertx
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/health-check-vertx
      fabric8.io/scm-tag: booster-parent-11
    labels:
      expose: "true"
      app: minecraft-server
      provider: fabric8
      version: 15-SNAPSHOT
      group: io.openshift.booster
    name: minecraft-server
  spec:
    type: LoadBalancer
    ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: 25565
      nodePort: 30000
    - name: http
      port: 7791
      protocol: TCP
      targetPort: 7791
    selector:
      app: minecraft-server
      provider: fabric8
      group: io.openshift.booster
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=health-check-vertx&var-version=15-SNAPSHOT
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/health-check-vertx
      fabric8.io/scm-url: https://github.com/openshiftio/health-check-vertx
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/health-check-vertx
      fabric8.io/scm-tag: booster-parent-11
    labels:
      app: minecraft-server
      provider: fabric8
      version: 15-SNAPSHOT
      group: io.openshift.booster
    name: minecraft-server
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: minecraft-server
      provider: fabric8
      group: io.openshift.booster
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Recreate
    template:
      metadata:
        annotations:
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=health-check-vertx&var-version=15-SNAPSHOT
          fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/health-check-vertx
          fabric8.io/scm-url: https://github.com/openshiftio/health-check-vertx
          fabric8.io/iconUrl: img/icons/vertx.svg
          fabric8.io/git-branch: master
          fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/health-check-vertx
          fabric8.io/scm-tag: booster-parent-11
        labels:
          app: minecraft-server
          provider: fabric8
          version: 15-SNAPSHOT
          group: io.openshift.booster
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAVA_OPTS
            value: >-
              -Xms756m -Xmx756m -XX:+UnlockExperimentalVMOptions
              -XX:+UseCGroupMemoryLimitForHeap -XX:+UseParallelGC
              -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4
          - name: MAVEN_OPTS
            value: >-
              -Xms128m -Xmx128m -XX:+UnlockExperimentalVMOptions
              -XX:+UseCGroupMemoryLimitForHeap -XX:+UseParallelGC
              -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4
          image: minecraft-server:latest
          imagePullPolicy: IfNotPresent
          name: minecraft-server
          ports:
          - containerPort: 7791
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 1G
            requests:
              cpu: '2'
              memory: 1G
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - minecraft-server
        from:
          kind: ImageStreamTag
          name: minecraft-server:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: minecraft-server
      provider: fabric8
      version: 15-SNAPSHOT
      group: io.openshift.booster
    name: minecraft-server
  spec:
    port:
      targetPort: 7791
    to:
      kind: Service
      name: minecraft-server
